keys:
  - &personal age1w3zqhmct9x58msl0r2ulfyj8u50f2dnu0qrg4yq6agz75te9ldfs7kelxd
  - &navis age10j4nuuhl584r2g9ty3wqd6ezylun7d89ryj77jgypw967yqkksvqr6484p
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *personal
          - *navis
