{inputs, ...}: {
  flake-file.inputs = {
    maki = {
      url = "github:tontinton/maki";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  flake.modules.homeManager."programs/maki" = {
    pkgs,
    config,
    lib,
    ...
  }: let
    inherit (config.lib.stylix.colors) withHashtag;

    # -- helpers to derive muted variants of the base16 palette ----------------
    # (uses the same `-rgb-{r,g,b}` channel access as modules/programs/browsers/firefox/custom-styles.nix)
    channel = base: suffix: lib.toInt config.lib.stylix.colors."${base}-${suffix}";

    hexDigits = "0123456789abcdef";

    # Nix has no modulo operator; use n - (n / d) * d
    intToHex = n:
      lib.substring (n / 16) 1 hexDigits
      + lib.substring (n - (n / 16) * 16) 1 hexDigits;

    # darken a base16 slot by num/denom (integer math, e.g. 35 100 = 35%)
    darken = base: num: denom: let
      r = (channel base "rgb-r") * num / denom;
      g = (channel base "rgb-g") * num / denom;
      b = (channel base "rgb-b") * num / denom;
    in "#${intToHex r}${intToHex g}${intToHex b}";

    # -- custom theme generated from the Stylix base16 palette ----------------
    themeToml = ''
      # Custom "stylix" theme generated by Nix from the Stylix base16 palette.
      # Palette slots map onto the standard base16 roles:
      #   base00 bg, base01 current_line, base02 selection, base03 comment,
      #   base05 fg, base08 red, base09 orange, base0A yellow, base0B green,
      #   base0C cyan, base0D blue, base0E purple/pink, base0F brown.

      "comment"                         = { fg = "comment" }
      "comment.block"                   = { fg = "comment" }
      "comment.block.documentation"     = { fg = "comment" }
      "comment.line"                    = { fg = "comment" }
      "comment.line.documentation"      = { fg = "comment" }

      "constant"                        = { fg = "purple" }
      "constant.builtin"                = { fg = "purple" }
      "constant.builtin.boolean"        = { fg = "purple" }
      "constant.character"              = { fg = "cyan" }
      "constant.character.escape"       = { fg = "pink" }
      "constant.macro"                  = { fg = "purple" }
      "constant.numeric"                = { fg = "purple" }
      "constructor"                     = { fg = "purple" }

      "error"                           = { fg = "red" }
      "warning"                         = { fg = "yellow" }
      "info"                            = { fg = "cyan" }
      "hint"                            = { fg = "purple" }

      "diff.delta"                      = { fg = "orange" }
      "diff.minus"                      = { fg = "red" }
      "diff.plus"                       = { fg = "green" }

      "function"                        = { fg = "blue" }
      "function.builtin"                = { fg = "blue" }
      "function.call"                   = { fg = "blue" }
      "function.macro"                  = { fg = "purple" }
      "function.method"                 = { fg = "blue" }

      "keyword"                         = { fg = "pink" }
      "keyword.control.conditional"     = { fg = "pink" }
      "keyword.control.exception"       = { fg = "purple" }
      "keyword.control.import"          = { fg = "pink" }
      "keyword.control.repeat"          = { fg = "pink" }
      "keyword.directive"               = { fg = "green" }
      "keyword.function"                = { fg = "pink" }
      "keyword.operator"                = { fg = "pink" }
      "keyword.return"                  = { fg = "pink" }
      "keyword.storage"                 = { fg = "pink" }
      "keyword.storage.modifier"        = { fg = "pink" }
      "keyword.storage.type"            = { fg = "cyan", modifiers = ["italic"] }

      "label"                           = { fg = "cyan" }
      "attribute"                       = { fg = "green", modifiers = ["italic"] }
      "namespace"                       = { fg = "foreground" }
      "annotation"                      = { fg = "foreground" }
      "operator"                        = { fg = "pink" }

      "markup.bold"                     = { fg = "orange", modifiers = ["bold"] }
      "markup.heading"                  = { fg = "purple", modifiers = ["bold"] }
      "markup.italic"                   = { fg = "yellow", modifiers = ["italic"] }
      "markup.link.text"                = { fg = "pink" }
      "markup.link.url"                 = { fg = "cyan" }
      "markup.list"                     = { fg = "cyan" }
      "markup.quote"                    = { fg = "yellow", modifiers = ["italic"] }
      "markup.raw"                      = { fg = "foreground" }
      "markup.strikethrough"            = { modifiers = ["crossed_out"] }

      "punctuation"                     = { fg = "foreground" }
      "punctuation.bracket"             = { fg = "foreground" }
      "punctuation.delimiter"           = { fg = "foreground" }
      "punctuation.special"             = { fg = "pink" }

      "special"                         = { fg = "pink" }

      "string"                          = { fg = "yellow" }
      "string.regexp"                   = { fg = "red" }
      "string.special"                  = { fg = "orange" }
      "string.symbol"                   = { fg = "yellow" }

      "tag"                             = { fg = "pink" }
      "tag.attribute"                   = { fg = "purple" }
      "tag.delimiter"                   = { fg = "foreground" }

      "type"                            = { fg = "cyan", modifiers = ["italic"] }
      "type.builtin"                    = { fg = "cyan" }
      "type.enum.variant"               = { fg = "foreground", modifiers = ["italic"] }

      "variable"                        = { fg = "foreground" }
      "variable.builtin"                = { fg = "purple", modifiers = ["italic"] }
      "variable.other"                  = { fg = "foreground" }
      "variable.other.member"           = { fg = "foreground" }
      "variable.parameter"              = { fg = "orange", modifiers = ["italic"] }

      [palette]
      background   = "${withHashtag.base00}"
      foreground   = "${withHashtag.base05}"
      comment      = "${withHashtag.base03}"
      cyan         = "${withHashtag.base0C}"
      green        = "${withHashtag.base0B}"
      orange       = "${withHashtag.base09}"
      pink         = "${withHashtag.base0E}"
      purple       = "${withHashtag.base0E}"
      red          = "${withHashtag.base08}"
      yellow       = "${withHashtag.base0A}"
      blue         = "${withHashtag.base0D}"
      brown        = "${withHashtag.base0F}"
      current_line = "${withHashtag.base01}"
      selection    = "${withHashtag.base02}"

      [ui]
      user               = { fg = "cyan" }
      assistant          = { fg = "foreground" }
      assistant_prefix   = { fg = "pink" }
      thinking           = { fg = "comment", modifiers = ["italic"] }
      tool_bg            = { bg = "${darken "base00" 88 100}" }
      tool               = { fg = "foreground" }
      tool_path          = { fg = "orange" }
      tool_annotation    = { fg = "comment" }
      tool_prefix        = { fg = "foreground", modifiers = ["bold"] }
      tool_success       = { fg = "green" }
      tool_error         = { fg = "red" }
      tool_dim           = { fg = "comment" }
      error              = { fg = "red" }
      status_dim         = { fg = "comment" }
      strikethrough      = { fg = "comment", modifiers = ["crossed_out"] }
      plan_rule          = { fg = "pink", modifiers = ["bold"] }
      code_block         = { fg = "foreground" }
      horizontal_rule    = { fg = "comment" }
      table_border       = { fg = "comment" }
      diff_old           = { bg = "${darken "base08" 35 100}" }
      diff_new           = { bg = "${darken "base0B" 35 100}" }
      diff_old_emphasis  = { bg = "${darken "base08" 50 100}" }
      diff_new_emphasis  = { bg = "${darken "base0B" 50 100}" }
      diff_line_nr       = { fg = "comment" }
      todo_completed     = { fg = "green" }
      todo_in_progress   = { fg = "yellow" }
      todo_pending       = { fg = "comment" }
      todo_cancelled     = { fg = "red", modifiers = ["crossed_out"] }
      item_selected      = { fg = "background", bg = "purple" }
      item               = { fg = "cyan" }
      item_desc          = { fg = "comment" }
      accent             = { fg = "orange" }
      panel_border       = { fg = "purple" }
      panel_title        = { fg = "purple", modifiers = ["bold"] }
      cursor             = { fg = "background", bg = "foreground" }
      keybind_key        = { fg = "cyan", modifiers = ["bold"] }
      keybind_section    = { fg = "purple", modifiers = ["bold"] }
      input_border       = { fg = "comment" }
      keybind_desc       = { fg = "foreground" }
      queue              = { fg = "purple" }
      plan_path          = { fg = "orange", modifiers = ["bold"] }
      status_notice      = { fg = "orange" }
      status_retry_error = { fg = "red" }
      status_retry_info  = { fg = "comment" }
      input_placeholder  = { fg = "comment" }
      queue_delete       = { fg = "red", modifiers = ["bold"] }
      timestamp          = { fg = "comment" }
      spinner            = { fg = "yellow" }
      active             = { fg = "cyan" }
      progress_bar       = { fg = "cyan", bg = "background" }
      shell_prefix       = { fg = "yellow", modifiers = ["bold"] }
    '';
  in {
    home.packages = [inputs.maki.packages.${pkgs.stdenv.hostPlatform.system}.default];

    # Custom theme derived from the Stylix base16 palette (base00-base0F).
    home.file.".config/maki/themes/stylix.toml".text = themeToml;

    # Force-apply the stylix theme on every startup, overriding any
    # interactively-selected theme. Add more `maki.setup()` options here if needed.
    home.file.".config/maki/init.lua".text = ''
      -- Managed by Nix. Extend this file with more maki.setup() options if needed.
      maki.setup({
          ui = {
              theme = "stylix",
          },
      })
    '';
  };
}